export const metadata = {
  title: 'Haynrikh Santrosyan',
  description: 'Generated by Next.js',
  icons: {
    icon: '/logo.svg',
   },
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
